// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/specta-rs/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async openVault(path: string) : Promise<Result<VaultConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_vault", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createVault(path: string, name: string) : Promise<Result<VaultConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_vault", { path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateVaultPath(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_vault_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readDirectory(path: string) : Promise<Result<FileEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_directory", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(path: string, vaultPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeFile(path: string, content: string, vaultPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { path, content, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFile(path: string, vaultPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_file", { path, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFile(path: string, vaultPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_file", { path, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameFile(oldPath: string, newPath: string, vaultPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_file", { oldPath, newPath, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(path: string, vaultPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { path, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllNotes(vaultPath: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_notes", { vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGithubActivity(date: string) : Promise<Result<GitHubActivityResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_github_activity", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getJiraToken() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_jira_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setJiraToken(token: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_jira_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeJiraToken() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_jira_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listClaudeProjects() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_claude_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClaudeActivities(date: string, subscribedFolders: string[]) : Promise<Result<ClaudeActivityResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_claude_activities", { date, subscribedFolders }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClaudeActivityDates(subscribedFolders: string[], year: number, month: number) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_claude_activity_dates", { subscribedFolders, year, month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkWhisperModel() : Promise<Result<ModelStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_whisper_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadWhisperModel() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_whisper_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelWhisperDownload() : Promise<void> {
    await TAURI_INVOKE("cancel_whisper_download");
},
async cleanupPartialDownload() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_partial_download") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateAudioFile(filePath: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_audio_file", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcribeAudio(filePath: string) : Promise<Result<TranscriptionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelTranscription() : Promise<void> {
    await TAURI_INVOKE("cancel_transcription");
},
async saveRecordedAudio(audioData: number[]) : Promise<Result<SavedRecordingInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_recorded_audio", { audioData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanupRecording(filePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_recording", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRecordings() : Promise<Result<RecordingFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_recordings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startRealtimeTranscription(config: RealtimeTranscriptionConfig | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_realtime_transcription", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pushAudioChunk(samples: number[]) : Promise<Result<RealtimePartialResult | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_audio_chunk", { samples }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopRealtimeTranscription() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_realtime_transcription") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRealtimeTranscriptionActive() : Promise<boolean> {
    return await TAURI_INVOKE("is_realtime_transcription_active");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ClaudeActivityItem = { kind: ClaudeActivityKind; content: string; timestamp: string; project_path: string; session_id: string }
export type ClaudeActivityKind = "user" | "assistant"
export type ClaudeActivityResponse = { date: string; items: ClaudeActivityItem[] }
export type FileEntry = { name: string; path: string; is_dir: boolean; children: FileEntry[] | null }
export type GitHubActivityItem = { kind: GitHubActivityKind; title: string; url: string; repo: string; timestamp: string; number: number | null; summary: string | null }
export type GitHubActivityKind = "commit" | "pull_request" | "review" | "comment"
export type GitHubActivityResponse = { login: string; date: string; items: GitHubActivityItem[] }
export type ModelStatus = { is_installed: boolean; model_path: string | null; model_size: number | null }
export type RealtimePartialResult = { text: string; is_final: boolean; segment_index: number }
export type RealtimeTranscriptionConfig = { language: string | null }
export type RecordingFile = { file_path: string; file_name: string; file_size: number; created_at: number }
export type SavedRecordingInfo = { file_path: string; file_size: number }
export type TranscriptionResult = { text: string; duration_ms: number }
export type VaultConfig = { path: string; name: string }

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type Webview as __Webview__ } from "@tauri-apps/api/webview";
import { type Window as __Window__ } from "@tauri-apps/api/window";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
  ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
  : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

export function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  const result = {} as {
    [K in keyof T]: __EventObj__<T[K]> & {
      (window: __Webview__ | __Window__): __EventObj__<T[K]>;
    };
  };

  for (const key in mappings) {
    const name = mappings[key];

    const base: __EventObj__<any> = {
      listen: (cb) => TAURI_API_EVENT.listen(name, cb),
      once: (cb) => TAURI_API_EVENT.once(name, cb),
      emit: (payload: any) => TAURI_API_EVENT.emit(name, payload),
    };

    const withWindow = (window: __Webview__ | __Window__): __EventObj__<any> => ({
      listen: (cb) => window.listen(name, cb),
      once: (cb) => window.once(name, cb),
      emit: (payload: any) => window.emit(name, payload),
    });

    result[key] = Object.assign(withWindow, base);
  }

  return result;
}

