// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/specta-rs/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openVault(path: string) : Promise<Result<VaultConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_vault", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createVault(path: string, name: string) : Promise<Result<VaultConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_vault", { path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateVaultPath(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_vault_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ipcHealthCheck(traceId: string | null) : Promise<Result<IpcHealthResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ipc_health_check", { traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readDirectory(path: string) : Promise<Result<FileEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_directory", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(path: string, vaultPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeFile(path: string, content: string, vaultPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { path, content, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFile(path: string, vaultPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_file", { path, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFile(path: string, vaultPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_file", { path, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameFile(oldPath: string, newPath: string, vaultPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_file", { oldPath, newPath, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(path: string, vaultPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { path, vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllNotes(vaultPath: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_notes", { vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGithubActivity(date: string, traceId: string | null) : Promise<Result<GitHubActivityResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_github_activity", { date, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getJiraToken(traceId: string | null) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_jira_token", { traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setJiraToken(token: string, traceId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_jira_token", { token, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeJiraToken(traceId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_jira_token", { traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async jiraTestConnection(params: JiraRequestInput, traceId: string | null) : Promise<Result<JiraTestConnectionResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_test_connection", { params, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async jiraListIssues(params: JiraRequestInput, traceId: string | null) : Promise<Result<JiraIssuesListResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_list_issues", { params, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatCheckStatus() : Promise<Result<ChatStatusResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_check_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatStartStream(input: ChatStreamStartInput, traceId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_start_stream", { input, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatCancelStream(requestId: string, traceId: string | null) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_cancel_stream", { requestId, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listClaudeProjects(traceId: string | null) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_claude_projects", { traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClaudeActivities(date: string, subscribedFolders: string[], traceId: string | null) : Promise<Result<ClaudeActivityResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_claude_activities", { date, subscribedFolders, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClaudeActivityDates(subscribedFolders: string[], year: number, month: number, traceId: string | null) : Promise<Result<number[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_claude_activity_dates", { subscribedFolders, year, month, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googlePrepareOauth(state: string, traceId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_prepare_oauth", { state, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googlePollOauthResult(state: string, traceId: string | null) : Promise<Result<GoogleAuthResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_poll_oauth_result", { state, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googleExchangeToken(params: GoogleTokenExchangeInput, traceId: string | null) : Promise<Result<HttpProxyResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_exchange_token", { params, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googleListEvents(params: GoogleEventsInput, traceId: string | null) : Promise<Result<HttpProxyResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_list_events", { params, traceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { code: string; message: string; retryable: boolean; traceId: string; source: string }
export type ChatStatusResponse = { status: string; version: string | null; error: string | null }
export type ChatStreamStartInput = { requestId: string; message: string; workingDirectory: string | null; sessionId: string | null; systemPrompt: string | null; conversationId: string | null }
export type ClaudeActivityItem = { kind: ClaudeActivityKind; content: string; timestamp: string; project_path: string; session_id: string }
export type ClaudeActivityKind = "user" | "assistant"
export type ClaudeActivityResponse = { date: string; items: ClaudeActivityItem[] }
export type FileEntry = { name: string; path: string; is_dir: boolean; children: FileEntry[] | null }
export type GitHubActivityItem = { kind: GitHubActivityKind; title: string; url: string; repo: string; timestamp: string; number: number | null; summary: string | null }
export type GitHubActivityKind = "commit" | "pull_request" | "review" | "comment"
export type GitHubActivityResponse = { login: string; date: string; items: GitHubActivityItem[] }
export type GoogleAuthResult = { status: string; code: string | null; error: string | null }
export type GoogleEventsInput = { accessToken: string; calendarId: string | null; timeMin: string | null; timeMax: string | null; syncToken: string | null; pageToken: string | null; maxResults: number | null }
export type GoogleTokenExchangeInput = { grantType: string; code: string | null; codeVerifier: string | null; refreshToken: string | null; redirectUri: string; clientId: string; clientSecret: string | null }
export type HttpProxyResponse = { status: number; dataJson: string }
export type IpcHealthResponse = { status: string; timestamp: string; traceId: string }
export type JiraIssue = { key: string; summary: string; status: string; updated: string | null; assignee: string | null }
export type JiraIssuesListResponse = { issues: JiraIssue[] }
export type JiraRequestInput = { baseUrl: string; email: string; apiToken: string }
export type JiraTestConnectionResponse = { profile: JiraUserProfile }
export type JiraUserProfile = { displayName: string; emailAddress: string | null; accountId: string | null; avatarUrls: Partial<{ [key in string]: string }> | null }
export type VaultConfig = { path: string; name: string }

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type Webview as __Webview__ } from "@tauri-apps/api/webview";
import { type Window as __Window__ } from "@tauri-apps/api/window";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
  ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
  : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

export function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  const result = {} as {
    [K in keyof T]: __EventObj__<T[K]> & {
      (window: __Webview__ | __Window__): __EventObj__<T[K]>;
    };
  };

  for (const key in mappings) {
    const name = mappings[key];

    const base: __EventObj__<any> = {
      listen: (cb) => TAURI_API_EVENT.listen(name, cb),
      once: (cb) => TAURI_API_EVENT.once(name, cb),
      emit: (payload: any) => TAURI_API_EVENT.emit(name, payload),
    };

    const withWindow = (window: __Webview__ | __Window__): __EventObj__<any> => ({
      listen: (cb) => window.listen(name, cb),
      once: (cb) => window.once(name, cb),
      emit: (payload: any) => window.emit(name, payload),
    });

    result[key] = Object.assign(withWindow, base);
  }

  return result;
}

